server:
  port: 7071
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
  application:
    name: Bibibi-web
  datasource:
    url: jdbc:mysql://192.168.80.132:3306/Bibibi?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 192.168.80.132
    port: 6379
    password: aaa123
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000
#mybatis 大小写转驼峰
mybatis:
  configuration:
    map-underscore-to-camel-case: true

project:
  folder: d:/DESKTOP/
log:
  root:
    level: debug
admin:
  account: admin
  password: admin123

showFFmegLog: true

es:
  host:
    port: 192.168.80.132:9200
  index:
    video:
      name: bibibi_video